{
  "name": "MindFull Horizon",
  "buildCommand": "pip install --no-cache-dir --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt",
  "startCommand": "gunicorn --worker-class eventlet --workers 1 --bind 0.0.0.0:$PORT app:app",
  "environments": [
    {
      "name": "production",
      "environmentVariables": {
        "FLASK_ENV": "production",
        "PYTHONPATH": ".",
        "SECRET_KEY": "${{ secrets.SECRET_KEY }}",
        "GEMINI_API_KEY": "${{ secrets.GEMINI_API_KEY }}",
        "DATABASE_URL": "${{ secrets.DATABASE_URL }}",
        "DISABLE_LOCAL_AI": "true"
      }
    }
  ],
  "buildFilter": {
    "ignoredPaths": ["/.git", "/.github", "/docs", "/tests", "/*.md", "/.ebextensions", "/docker-compose.yml", "/nginx.conf", "/deploy_helper.sh", "/Procfile.alternatives"]
  }
}
